CREATE TABLE users(
    id SERIAL PRIMARY KEY,
    login VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(500) NOT NULL
);

CREATE TABLE refreshsessions(
    id SERIAL PRIMARY KEY,
    user_login VARCHAR(100) NOT NULL REFERENCES users(login) ON UPDATE CASCADE ON DELETE CASCADE,
    fingerprint VARCHAR(300) NOT NULL,
    refreshtoken VARCHAR(300) NOT NULL,
    exp TIMESTAMP NOT NULL,
    iat TIMESTAMP NOT NULL
);

CREATE TABLE groups(
    id SERIAL PRIMARY KEY,
    user_login VARCHAR(100) NOT NULL REFERENCES users(login) ON UPDATE CASCADE ON DELETE CASCADE,
    name VARCHAR(100) NOT NULL
);

CREATE TABLE notes(
    id SERIAL PRIMARY KEY,
    user_login VARCHAR(100) NOT NULL REFERENCES users(login) ON UPDATE CASCADE ON DELETE CASCADE,
    title VARCHAR(100) NOT NULL,
    text VARCHAR(10485760),
    group_id INTEGER REFERENCES groups(id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE ROLE notesapp WITH
    LOGIN;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO notesapp;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO notesapp;